"""
domains.flashcards.tools — LLM-callable tools for the flashcards domain.

Extracted from the original ``llm_agent.py`` monolith.  Each tool
corresponds to one OpenAI/DeepSeek tool definition registered into
:class:`agent.tool_registry.ToolRegistry` by :func:`register`.

Naming
------
The tool names match the prefixes the LLM expects (see
``agent.prompts.SYSTEM_PROMPT``):

* ``flashcard_*`` — conceptual flashcards (the only kind the LLM can
  manage directly; factual and Notion cards live in Notion).
* ``course_*`` — read-only course listing.

Why not read factual / Notion cards?
------------------------------------
The original SYSTEM_PROMPT tells the LLM: "Solo puedes gestionar
flashcards CONCEPTUALES. Las factuales y de Notion son de solo
lectura (viven en Notion)."  ``flashcard_list`` and
``flashcard_search`` *do* return factual/Notion cards (with a
``card_type`` discriminator) so the LLM can answer questions about
them, but it must not edit or delete them.
"""
from __future__ import annotations

import sqlite3
from datetime import date
from typing import Callable, Iterable, Optional

from agent.tool_registry import ToolRegistry
from core.db import get_state_conn

from . import storage


# --------------------------------------------------------------------------- #
# Tool implementations
# --------------------------------------------------------------------------- #
def tool_flashcard_create_conceptual(course: str, front: str, back: str = "") -> dict:
    """Create a conceptual flashcard.

    The card starts with default SRS state (ease=2.5, interval=0,
    repetitions=0, next_review=today) — same as the original.
    """
    if not course or not course.strip():
        return {"status": "error", "message": "El nombre del curso no puede estar vacío"}
    if not front or not front.strip():
        return {"status": "error", "message": "El front (pregunta) no puede estar vacío"}
    today = date.today().isoformat()
    course = course.strip()
    front = front.strip()
    try:
        conn = get_state_conn()
        conn.execute(
            "INSERT INTO course_flashcards "
            "(front, back, course, card_type, ease, interval, repetitions, next_review) "
            "VALUES (?, ?, ?, 'conceptual', 2.5, 0, 0, ?)",
            (front, back, course, today),
        )
        conn.commit()
        cid = conn.execute("SELECT last_insert_rowid()").fetchone()[0]
        conn.close()
        return {
            "status": "ok",
            "message": f"🧠 Flashcard conceptual creada en '{course}'",
            "flashcard_id": cid,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_list(
    course: Optional[str] = None,
    card_type: Optional[str | Iterable[str]] = None,
) -> dict:
    """List flashcards, optionally filtered by course and/or card_type.

    ``card_type`` may be a single string or a list/tuple (the LLM
    sometimes sends lists in the arguments payload).
    """
    try:
        conn = get_state_conn()
        q = (
            "SELECT id, front, back, course, card_type, ease, interval, "
            "repetitions, next_review FROM course_flashcards"
        )
        params: list = []
        where: list[str] = []
        if course:
            where.append("course=?")
            params.append(course)
        if card_type:
            if isinstance(card_type, (list, tuple)):
                ph = ",".join("?" for _ in card_type)
                where.append(f"card_type IN ({ph})")
                params.extend(card_type)
            else:
                where.append("card_type=?")
                params.append(card_type)
        if where:
            q += " WHERE " + " AND ".join(where)
        q += " ORDER BY next_review ASC"
        rows = conn.execute(q, params).fetchall()
        conn.close()
        today_s = date.today().isoformat()
        results = [dict(r) for r in rows]
        due = sum(1 for r in results if str(r.get("next_review", "2000-01-01")) <= today_s)
        return {"total": len(results), "due": due, "flashcards": results}
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_edit(
    flashcard_id: int,
    front: Optional[str] = None,
    back: Optional[str] = None,
) -> dict:
    """Edit a flashcard's front or back.

    Only conceptual cards can be edited.  Notion-sourced cards (and
    factual cards generated by the old SRS) are read-only — the LLM
    must tell the user to update them in Notion instead.
    """
    try:
        conn = get_state_conn()
        row = conn.execute(
            "SELECT front, back, card_type FROM course_flashcards WHERE id=?",
            (flashcard_id,),
        ).fetchone()
        if not row:
            conn.close()
            return {"status": "error", "message": f"Flashcard #{flashcard_id} no encontrada"}
        if row["card_type"] != "conceptual":
            conn.close()
            return {
                "status": "error",
                "message": f"Flashcard #{flashcard_id} no es conceptual. No puedes editarla.",
            }
        updates: list[str] = []
        params: list = []
        if front is not None:
            updates.append("front=?")
            params.append(front)
        if back is not None:
            updates.append("back=?")
            params.append(back)
        if not updates:
            conn.close()
            return {"status": "error", "message": "Nada que editar"}
        params.append(flashcard_id)
        conn.execute(
            f"UPDATE course_flashcards SET {', '.join(updates)} WHERE id=?",
            params,
        )
        conn.commit()
        conn.close()
        return {"status": "ok", "message": f"✏️ Flashcard #{flashcard_id} actualizada"}
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_delete(flashcard_id: int) -> dict:
    """Delete a flashcard.  DESTRUCTIVE — only conceptual allowed.

    Marked ``destructive=True`` at registration time so the agent
    surfaces Confirm/Cancel buttons before executing.
    """
    try:
        conn = get_state_conn()
        row = conn.execute(
            "SELECT front, card_type FROM course_flashcards WHERE id=?",
            (flashcard_id,),
        ).fetchone()
        if not row:
            conn.close()
            return {"status": "error", "message": f"Flashcard #{flashcard_id} no encontrada"}
        if row["card_type"] != "conceptual":
            conn.close()
            return {
                "status": "error",
                "message": (
                    f"Solo puedes eliminar flashcards conceptuales. "
                    f"Esta es '{row['card_type']}'."
                ),
            }
        front = row["front"]
        conn.execute("DELETE FROM course_flashcards WHERE id=?", (flashcard_id,))
        conn.commit()
        conn.close()
        return {
            "status": "ok",
            "message": f"🗑️ Flashcard eliminada: '{front}' (#{flashcard_id})",
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_reset_srs(flashcard_id: int) -> dict:
    """Reset the SRS state of a flashcard to defaults (ease=2.5, etc.).

    Useful when the user wants to re-learn a card from scratch.
    """
    try:
        conn = get_state_conn()
        row = conn.execute(
            "SELECT front FROM course_flashcards WHERE id=?",
            (flashcard_id,),
        ).fetchone()
        if not row:
            conn.close()
            return {"status": "error", "message": f"Flashcard #{flashcard_id} no encontrada"}
        today_s = date.today().isoformat()
        conn.execute(
            "UPDATE course_flashcards "
            "SET ease=2.5, interval=0, repetitions=0, next_review=? WHERE id=?",
            (today_s, flashcard_id),
        )
        conn.commit()
        conn.close()
        return {
            "status": "ok",
            "message": f"🔄 SRS reset para '{row['front']}' (#{flashcard_id})",
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_courses() -> dict:
    """List every distinct course present in ``course_flashcards``."""
    try:
        names = storage.courses()
        return {"courses": names, "total": len(names)}
    except Exception as e:
        return {"status": "error", "message": str(e)}


def tool_flashcard_search(query: str, course: Optional[str] = None) -> dict:
    """Search flashcards by text content (matches front OR back).

    Capped at 50 results and ordered by course+id for stable pagination.
    """
    try:
        conn = get_state_conn()
        q = (
            "SELECT id, front, back, course, card_type, next_review "
            "FROM course_flashcards WHERE (front LIKE ? OR back LIKE ?)"
        )
        params: list = [f"%{query}%", f"%{query}%"]
        if course:
            q += " AND course=?"
            params.append(course)
        q += " ORDER BY course ASC, id ASC LIMIT 50"
        rows = conn.execute(q, params).fetchall()
        conn.close()
        results = [dict(r) for r in rows]
        return {"total": len(results), "query": query, "flashcards": results}
    except Exception as e:
        return {"status": "error", "message": str(e)}


# --------------------------------------------------------------------------- #
# Schemas (OpenAI / DeepSeek tool format)
# --------------------------------------------------------------------------- #
def _schema(name: str, description: str, properties: dict, required: list[str]) -> dict:
    """Tiny helper to keep the tool schema definitions DRY."""
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": description,
            "parameters": {
                "type": "object",
                "properties": properties,
                "required": required,
            },
        },
    }


_SCHEMAS: dict[str, dict] = {
    "flashcard_create_conceptual": _schema(
        name="flashcard_create_conceptual",
        description=(
            "Crea una flashcard conceptual en un curso. "
            "Úsala cuando el usuario quiera estudiar/recordar un concepto "
            "(no para vocabulario, no para datos puntuales)."
        ),
        properties={
            "course": {"type": "string", "description": "Nombre del curso."},
            "front": {"type": "string", "description": "Pregunta (anverso)."},
            "back": {"type": "string", "description": "Respuesta (reverso). Opcional."},
        },
        required=["course", "front"],
    ),
    "flashcard_list": _schema(
        name="flashcard_list",
        description=(
            "Lista flashcards. Puede filtrar por curso y/o card_type "
            "('conceptual', 'factual', 'notion', 'notion_reversed')."
        ),
        properties={
            "course": {"type": "string", "description": "Filtrar por curso (opcional)."},
            "card_type": {
                "type": "string",
                "description": "Filtrar por tipo (opcional).",
            },
        },
        required=[],
    ),
    "flashcard_edit": _schema(
        name="flashcard_edit",
        description=(
            "Edita el front o back de una flashcard conceptual. "
            "NO funciona con flashcards factuales o de Notion."
        ),
        properties={
            "flashcard_id": {"type": "integer", "description": "ID de la flashcard."},
            "front": {"type": "string", "description": "Nuevo front (opcional)."},
            "back": {"type": "string", "description": "Nuevo back (opcional)."},
        },
        required=["flashcard_id"],
    ),
    "flashcard_delete": _schema(
        name="flashcard_delete",
        description=(
            "Elimina una flashcard conceptual. DESTRUCTIVO: requiere "
            "confirmación del usuario. NO funciona con factuales/Notion."
        ),
        properties={
            "flashcard_id": {"type": "integer", "description": "ID de la flashcard a eliminar."},
        },
        required=["flashcard_id"],
    ),
    "flashcard_reset_srs": _schema(
        name="flashcard_reset_srs",
        description=(
            "Resetea el estado SRS (ease, interval, repetitions, next_review) "
            "de una flashcard a los valores iniciales para re-aprenderla."
        ),
        properties={
            "flashcard_id": {"type": "integer", "description": "ID de la flashcard."},
        },
        required=["flashcard_id"],
    ),
    "flashcard_courses": _schema(
        name="flashcard_courses",
        description="Lista todos los cursos que tienen flashcards.",
        properties={},
        required=[],
    ),
    "flashcard_search": _schema(
        name="flashcard_search",
        description=(
            "Busca flashcards por texto en front o back. "
            "Incluye conceptuales, factuales y de Notion."
        ),
        properties={
            "query": {"type": "string", "description": "Texto a buscar."},
            "course": {"type": "string", "description": "Filtrar por curso (opcional)."},
        },
        required=["query"],
    ),
}


# --------------------------------------------------------------------------- #
# Tool dispatcher (name -> callable)
# --------------------------------------------------------------------------- #
_TOOL_FNS: dict[str, Callable] = {
    "flashcard_create_conceptual": tool_flashcard_create_conceptual,
    "flashcard_list": tool_flashcard_list,
    "flashcard_edit": tool_flashcard_edit,
    "flashcard_delete": tool_flashcard_delete,
    "flashcard_reset_srs": tool_flashcard_reset_srs,
    "flashcard_courses": tool_flashcard_courses,
    "flashcard_search": tool_flashcard_search,
}


# Tools that mutate user data — the agent should route these through
# its confirmation flow before invoking them.
_DESTRUCTIVE: frozenset[str] = frozenset({"flashcard_delete"})


# --------------------------------------------------------------------------- #
# Public registration entry point
# --------------------------------------------------------------------------- #
def register(registry: ToolRegistry) -> None:
    """Register every flashcard tool into ``registry``.

    The application entry point is expected to call this once, at
    startup, before instantiating the agent.
    """
    for name, fn in _TOOL_FNS.items():
        registry.add(
            name=name,
            fn=fn,
            schema=_SCHEMAS[name],
            destructive=(name in _DESTRUCTIVE),
        )


__all__ = [
    "register",
    "tool_flashcard_create_conceptual",
    "tool_flashcard_list",
    "tool_flashcard_edit",
    "tool_flashcard_delete",
    "tool_flashcard_reset_srs",
    "tool_flashcard_courses",
    "tool_flashcard_search",
]
